services:
  bot:
    build: .
    container_name: bingx_bot
    env_file:
      - .env  
    volumes:
      - .:/app  
      - ./notify_chats.json:/app/notify_chats.json  
    restart: on-failure
    network_mode: "bridge"